In [11]:
import pandas as pd
from sklearn import datasets

In [12]:
iris = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

In [16]:
iris.groupby("species").describe()

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [21]:
%%markdown
# Indexing

# Indexing

In [23]:
iris[1:3]['sepal_length']

1    4.9
2    4.7
Name: sepal_length, dtype: float64

In [24]:
# iloc

iris.iloc[:4, 1:3]

   sepal_width  petal_length
0          3.5           1.4
1          3.0           1.4
2          3.2           1.3
3          3.1           1.5

In [25]:
iris[['petal_length', 'petal_width']]

     petal_length  petal_width
0             1.4          0.2
1             1.4          0.2
2             1.3          0.2
3             1.5          0.2
4             1.4          0.2
..            ...          ...
145           5.2          2.3
146           5.0          1.9
147           5.2          2.0
148           5.4          2.3
149           5.1          1.8

[150 rows x 2 columns]

In [29]:
iris[iris.petal_length > 5]

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica